version: '3.8'

services:

  currency-service:
    build: back/currency-service
    ports:
      - "8006:8006"
    networks:
      - back

  currency-bff:
    build: back/currency-bff
    depends_on:
      currency-service:
        condition: service_healthy
    environment:
      - OPENAPIDEFINITION_URL=http://currency-service:8006
      - RATESCONTROLLER_URL=http://currency-service:8006
    ports:
      - "8007:8007"
    networks:
      - back

#  currency-front:
#    build: front/currency-front
#    depends_on:
#      currency-bff:
#        condition: service_healthy
#    ports:
#      - "3000:3000"
#    networks:
#      - front
#      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
