/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CurrenciesDate
 */
export interface CurrenciesDate {
    /**
     * 
     * @type {string}
     * @memberof CurrenciesDate
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesDate
     */
    currency?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof CurrenciesDate
     */
    values?: { [key: string]: number; };
}
