/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.33).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.company.rates.swagger.api;

import com.company.rates.swagger.model.CurrenciesDate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
@Api(value = "RatesController", description = "the RatesController API")
public interface RatesControllerApi {

    @ApiOperation(value = "", nickname = "getCurrencies", notes = "", response = String.class, responseContainer = "List", tags={ "rates-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = String.class, responseContainer = "List") })
    @RequestMapping(value = "/rates/{date}/currencies",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<String>> getCurrencies(@ApiParam(value = "", required=true) @PathVariable("date") String date);


    @ApiOperation(value = "", nickname = "getRateByCharCode", notes = "", response = CurrenciesDate.class, tags={ "rates-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CurrenciesDate.class) })
    @RequestMapping(value = "/rates/{date}/{currencyCode}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<CurrenciesDate> getRateByCharCode(@ApiParam(value = "", required=true) @PathVariable("date") String date, @ApiParam(value = "", required=true) @PathVariable("currencyCode") String currencyCode);

}

