server:
    port: ${PORT:8007}

feign:
    client:
        config:
            default:
                loggerLevel: full
logging:
    level:
        com:
            company:
                client: DEBUG

openAPIDefinition:
    url: ${OPENAPIDEFINITION_URL:#{'http://localhost:8006'}}

bff:
    rest:
        api:
            prefix: bff