server:
    port: 8007
debug: true

feign:
    client:
        config:
            default:
                loggerLevel: full
logging:
    level:
        com:
            company:
                client: DEBUG

openAPIDefinition:
    url: http://localhost:8006
ratesController:
    url: http://localhost:8086

bff:
    rest:
        api:
            prefix: bff