server:
    port: ${PORT:8007}

debug: true

feign:
    client:
        config:
            default:
                loggerLevel: full
    httpclient:
        disable-ssl-validation: true

    compression:
        request:
            enabled: 'true'
            min-request-size: '2048'
            mime-types: text/xml,application/xml,application/json
        response:
            enabled: 'true'

logging:
    level:
        com:
            company:
                client: DEBUG

openAPIDefinition:
    url: ${OPENAPIDEFINITION_URL:#{'http://localhost:8006'}}

bff:
    rest:
        api:
            prefix: bff