server:
  port: 8006

cdn:
  url: "https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1"

app:
  rest:
    api:
      prefix: /rates

spring:
  cache:
    caffeine:
      spec: maximumSize=3,expireAfterAccess=24h

logging:
  level:
    com:
      company:
        currency:
          client:
            cdn: DEBUG
  file:
    name: logs/currency-service.log
