/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CurrenciesDate
 */
export interface CurrenciesDate {
    /**
     * 
     * @type {string}
     * @memberof CurrenciesDate
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesDate
     */
    'currency'?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof CurrenciesDate
     */
    'values'?: { [key: string]: number; };
}

